### ISSUE TITLE
subscript out of bounds

### ISSUE THREAD

**Issue by ChlorisF** [JimGrange/flankr#2]
Hi Jim,

Thanks for the neat package! I conducted a flanker task on emotion recognition and tried to analyse data using the flankr package. I followed the step-by-step guide [https://www.youtube.com/watch?v=WYSh6YtP2Qs](url) and even renamed my variables just in case. However, I keep running into this problem:
Error in `[<-`(`*tmp*`, i, , value = correctProportions * accuracy) : 
  subscript out of bounds

Here is my code:

```
EF_dat <- dat %>%
  select(ID, item, Correct, RT, Match)
EF_dat <- EF_dat %>% 
  rename(accuracy = Correct, congruency = Match, condition = item, rt = RT)
head(EF_dat)
fit_EF <- fitDSTP(data = EF_dat, conditionName = "Angry")
```

<img src="https://user-images.githubusercontent.com/103331766/179122474-112a385c-6ee9-4d2c-a5b4-398a066dc8b5.png" width="500" />

As you can see in the image above, my data is very similar to your sample data except that I have Angry and Happy as two conditions. The error message should indicate that I tried to access a row or column that doesn’t exist, but I have no idea what might have caused the problem and how to fix it. Do you have solutions in mind? Any help is much appreciated!

**Comment by JimGrange** [comment]
Hello, 

Thanks for your interest in the package. Your ID column should be called "subject". Sorry for this; I should have been more flexible in allowing the user to choose how to label their own columns. 

To rename your column, do the following (using dplyr):

`EF_dat <- EF_dat %>% 
  rename(subject = ID)`

That should then work, but if not please let me know.

**Comment by ChlorisF** [comment]
Hi Jim,

Thanks a lot for your correction. I somehow didn't notice the title problem earlier, many apologies! The model fit runs smoothly after changing "ID" to "subject". However, I got a somewhat weird problem afterwards - when I tried to plot it, there were only dots (see figure below)... 
<img src="https://user-images.githubusercontent.com/103331766/179837287-1c17f99b-1159-4860-b158-e76d62c9c6f3.png" width="500" />
Could you advise on potential reasons for this? Sorry for the delayed response from my side. Many thanks!

Chloris

**Comment by JimGrange** [comment]
Hi Chloris, 

Would you mind creating another issue for this, please? That way other people can track each issue that has arisen and its solution.
